### **Cleaning Health and Retirement Study (HRS) 2024**

In [68]:
hrs_leisure_raw = pd.read_csv("data/hrs_data/h24lb_r.csv", dtype={"HHID": str, "PN": str})
hrs_cognition_raw = pd.read_csv("data/hrs_data/h24d_r.csv", dtype={"HHID": str, "PN": str})
hrs_health_raw = pd.read_csv("data/hrs_data/h24c_r.csv",dtype={"HHID": str, "PN": str})
hrs_demographics_raw = pd.read_csv("data/hrs_data/h24a_r.csv",dtype={"HHID": str, "PN": str})

display(duckdb.sql("SELECT * FROM hrs_leisure_raw LIMIT 5").df())
display(duckdb.sql("SELECT * FROM hrs_cognition_raw LIMIT 5").df())
display(duckdb.sql("SELECT * FROM hrs_health_raw LIMIT 5").df())
display(duckdb.sql("SELECT * FROM hrs_demographics_raw LIMIT 5").df())

,HHID,PN,TSUBHH,SSUBHH,TPN_SP,TCSR,TFAMR,TFINR,TLBRTYPE,TLBELIG,...,TLB0583B,TLB0584A,TLB0584B,TLB059A,TLB059B,TLB059C,TLB059D,TLB060,TVDATE,TVERSION
0,010004,040,1,1.0,NaN,1,1,1,95,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1
1,010013,040,1,1.0,NaN,1,1,1,95,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1
2,010038,010,0,0.0,40.0,1,5,1,95,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1
3,010038,040,0,0.0,10.0,5,1,5,95,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1
4,010050,010,0,0.0,NaN,1,1,1,95,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1

,HHID,PN,TSUBHH,SSUBHH,TPN_SP,TCSR,TFAMR,TFINR,TD190,TD101,...,TD551,TD552,TD553,TD554,TD555,TD556,TD557,TDMODE,TVDATE,TVERSION
0,010004,040,1,1.0,NaN,1,1,1,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,1
1,010013,040,1,1.0,NaN,1,1,1,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1
2,010038,010,0,0.0,40.0,1,5,1,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1
3,010038,040,0,0.0,10.0,5,1,5,1.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1
4,010050,010,0,0.0,NaN,1,1,1,1.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1

,HHID,PN,TSUBHH,SSUBHH,TPN_SP,TCSR,TFAMR,TFINR,TC231,TC234,...,TC177,TC178,TC179,TC180,TC181,TC182,TC183,TCMODE,TVDATE,TVERSION
0,010004,040,1,1.0,NaN,1,1,1,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,4.0,1
1,010013,040,1,1.0,NaN,1,1,1,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1
2,010038,010,0,0.0,40.0,1,5,1,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1
3,010038,040,0,0.0,10.0,5,1,5,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1
4,010050,010,0,0.0,NaN,1,1,1,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1

,HHID,PN,TSUBHH,SSUBHH,TPN_SP,TCSR,TFAMR,TFINR,TA500,TA501,...,TA066,TA068M,TA099,TA100,TA101,TA106,TA113,TAMODE,TVDATE,TVERSION
0,010004,040,1,1.0,NaN,1,1,1,6.0,2025.0,...,NaN,NaN,0.0,4.0,4.0,4.0,7.0,1.0,4.0,1
1,010013,040,1,1.0,NaN,1,1,1,2.0,2025.0,...,NaN,NaN,0.0,1.0,1.0,1.0,2.0,3.0,4.0,1
2,010038,010,0,0.0,40.0,1,5,1,2.0,2025.0,...,NaN,NaN,0.0,2.0,2.0,2.0,4.0,3.0,4.0,1
3,010038,040,0,0.0,10.0,5,1,5,2.0,2025.0,...,NaN,NaN,0.0,2.0,2.0,2.0,4.0,3.0,4.0,1
4,010050,010,0,0.0,NaN,1,1,1,9.0,2024.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1

We used HRS's 2024 [User Guide](data/hrs_data/h24dd.pdf) to determine which are the relevant variable to our research question in the dataframes. The HRS Core is divided into separate files based on questionnaire section. 
files: the Leave-Behind Questionnaire, Cognition, Physical Health, and Demographics.

### Relevant Variables
**Participant identifiers**
- `HHID`: household identification number
- `PN`: respondent person number within the household
When importing data we made both text strings because HRS specifically warns that identifiers such as HHID and PN may contain leading zeros and that users should preserve them when importing the data. 

**Leave-Behind Questionnaire (`h24lb_r.csv`)**
- `TLB001E`: frequency of attending an educational or training course
- `TLB001I`: frequency of reading books, magazines, or newspapers
- `TLB001J`: frequency of watching television
- `TLB001N`: frequency of using a computer for email, Internet, or other tasks
- `TLB001S`: frequency of playing sports or exercising
- `TLB001T`: frequency of walking for 20 minutes or more

The Leave-Behind Questionnaire is a self-administered survey that collects information about respondents' psychosocial characteristics and lifestyle activities. Although the questionnaire was introduced in 2004, in 2006 the design randomly selected approximately half of HRS households to respond, while the other half were selected in 2008. This alternating design continues across survey waves according to the User Guide.

Because the questionnaire is administered to a selected subset of respondents rather than the entire HRS sample, we expect a substantial number of missing values in these variables. However, not all selected respondents necessarily complete the questionnaire, and additional eligibility requirements may affect participation.

**Cognition (`h24d_r.csv`)**
- `TD174`: number of words correctly recalled during the immediate word-recall task
- `TD184`: number of words correctly recalled during the delayed word-recall task

**Physical Health (`h24c_r.csv`)**
- `TC083`: frequency of having trouble falling asleep
- `TC084`: frequency of waking during the night
- `TC085`: frequency of waking too early and being unable to fall asleep again
- `TC086`: frequency of feeling rested when waking in the morning
- `TC303`: minutes reported daily sitting time
- `TC304`: hours reported daily sitting time

**Demographics (`h24a_r.csv`)**
- `TA019`: respondent's current age

We will now create four smaller dataframes containing only the variables relevant to our analysis and rename the variables to make them easier to interpret.

In [ ]:
hrs_leisure = duckdb.sql("SELECT HHID AS hhid, PN AS pn, " \
"TLB001E AS education_training, " \
"TLB001I AS reading, TLB001J AS watching_tv, " \
"TLB001N AS computer_internet, TLB001S AS exercising, " \
"TLB001T AS walking FROM hrs_leisure_raw").df()

hrs_cognition = duckdb.sql("SELECT HHID AS hhid, PN AS pn, " \
"TD174 AS immediate_recall, " \
"TD184 AS delayed_recall FROM hrs_cognition_raw").df()

hrs_health = duckdb.sql("SELECT HHID AS hhid, PN AS pn, " \
"TC083 AS trouble_falling_asleep, " \
"TC084 AS waking_at_night, " \
"TC085 AS waking_too_early, " \
"TC086 AS feeling_rested, " \
"TC303 AS sitting_minutes, " \
"TC304 AS sitting_hours FROM hrs_health_raw").df()

hrs_demographics = duckdb.sql("SELECT HHID AS hhid, PN AS pn, " \
"TA019 AS age FROM hrs_demographics_raw").df()

display(hrs_leisure.head())
display(hrs_cognition.head())
display(hrs_health.head())
display(hrs_demographics.head())

,hhid,pn,education_training,reading,watching_tv,computer_internet,exercising,walking
0,010004,040,NaN,NaN,NaN,NaN,NaN,NaN
1,010013,040,NaN,NaN,NaN,NaN,NaN,NaN
2,010038,010,NaN,NaN,NaN,NaN,NaN,NaN
3,010038,040,NaN,NaN,NaN,NaN,NaN,NaN
4,010050,010,NaN,NaN,NaN,NaN,NaN,NaN

     hhid   pn  immediate_recall  delayed_recall
0  010004  040               8.0             8.0
1  010013  040               NaN             NaN
2  010038  010               NaN             NaN
3  010038  040               NaN             NaN
4  010050  010               5.0             3.0

,hhid,pn,trouble_falling_asleep,waking_at_night,waking_too_early,feeling_rested,sitting_minutes,sitting_hours
0,010004,040,3.0,3.0,3.0,1.0,0.0,5.0
1,010013,040,3.0,3.0,3.0,1.0,0.0,6.0
2,010038,010,3.0,3.0,3.0,2.0,-8.0,5.0
3,010038,040,2.0,2.0,3.0,1.0,-8.0,3.0
4,010050,010,2.0,3.0,3.0,2.0,0.0,6.0

     hhid   pn   age
0  010004  040  79.0
1  010013  040  77.0
2  010038  010  88.0
3  010038  040  81.0
4  010050  010  83.0

### Combining the HRS Dataframes

Although these variables are stored in separate CSV files, the files are all components of the same 2024 Health and Retirement Study data collection. HRS
separates its survey into files based on questionnaire section, such as leisure activities, cognition, physical health, and demographics.

Each respondent-level file contains `HHID` and `PN`. `HHID` identifies the respondent's household, while `PN` identifies the individual respondent within
that household. Together, these variables uniquely identify a respondent.

In [ ]:
hrs = duckdb.sql("SELECT l.*, c.* EXCLUDE (hhid, pn), h.* EXCLUDE (hhid, pn), d.* EXCLUDE (hhid, pn) FROM hrs_leisure AS l " \
"INNER JOIN hrs_cognition AS c USING (hhid, pn) " \
"INNER JOIN hrs_health AS h USING (hhid, pn) " \
"INNER JOIN hrs_demographics AS d USING (hhid, pn)").df()

display(hrs.head())

,hhid,pn,education_training,reading,watching_tv,computer_internet,exercising,walking,immediate_recall,delayed_recall,trouble_falling_asleep,waking_at_night,waking_too_early,feeling_rested,sitting_minutes,sitting_hours,age
0,010004,040,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,3.0,3.0,3.0,1.0,0.0,5.0,79.0
1,010013,040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,1.0,0.0,6.0,77.0
2,010038,010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,2.0,-8.0,5.0,88.0
3,010038,040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,1.0,-8.0,3.0,81.0
4,010050,010,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.0,2.0,3.0,3.0,2.0,0.0,6.0,83.0

### Overall Summary of the HRS Data

Before analyzing relationships between leisure activities and health or cognitive outcomes, we first summarize the combined HRS dataset. We calculate the number of participants and examine the frequency and percentage of responses for our main categorical variables, such as reading, television viewing, exercise, and sleep difficulties.

These statistics help us understand the composition of our sample and the distribution of each variable. They also allow us to identify uncommon, missing, or unusual response values that may need to be addressed before further analysis.

In [ ]:
num_participants = duckdb.sql("SELECT COUNT(DISTINCT (hhid, pn)) FROM hrs").fetchone()[0]
print("Number of participants:", num_participants)

reading_frequency = duckdb.sql("SELECT reading, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE reading IS NOT NULL " \
"GROUP BY reading ORDER BY reading").df()

tv_frequency = duckdb.sql("SELECT watching_tv, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE watching_tv IS NOT NULL " \
"GROUP BY watching_tv ORDER BY watching_tv").df()

computer_frequency = duckdb.sql("SELECT computer_internet, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE computer_internet IS NOT NULL " \
"GROUP BY computer_internet ORDER BY computer_internet").df()

exercise_frequency = duckdb.sql("SELECT exercising, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE exercising IS NOT NULL " \
"GROUP BY exercising ORDER BY exercising").df()

walking_frequency = duckdb.sql("SELECT walking, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE walking IS NOT NULL " \
"GROUP BY walking ORDER BY walking").df()

education_frequency = duckdb.sql("SELECT education_training, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE education_training IS NOT NULL " \
"GROUP BY education_training ORDER BY education_training").df()

falling_asleep_frequency = duckdb.sql("SELECT trouble_falling_asleep, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE trouble_falling_asleep IS NOT NULL " \
"GROUP BY trouble_falling_asleep ORDER BY trouble_falling_asleep").df()

waking_night_frequency = duckdb.sql("SELECT waking_at_night, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE waking_at_night IS NOT NULL " \
"GROUP BY waking_at_night ORDER BY waking_at_night").df()

waking_early_frequency = duckdb.sql("SELECT waking_too_early, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE waking_too_early IS NOT NULL " \
"GROUP BY waking_too_early ORDER BY waking_too_early").df()

rested_frequency = duckdb.sql("SELECT feeling_rested, COUNT(*) " \
"AS frequency, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) " \
"AS percentage FROM hrs WHERE feeling_rested IS NOT NULL " \
"GROUP BY feeling_rested ORDER BY feeling_rested").df()

display(reading_frequency)
display(tv_frequency)
display(computer_frequency)
display(exercise_frequency)
display(walking_frequency)
display(education_frequency)
display(falling_asleep_frequency)
display(waking_night_frequency)
display(waking_early_frequency)
display(rested_frequency)

Number of participants: 14398

   reading  frequency  percentage
0      1.0       1253       38.35
1      2.0        644       19.71
2      3.0        224        6.86
3      4.0        349       10.68
4      5.0        309        9.46
5      6.0        221        6.76
6      7.0        267        8.17

   watching_tv  frequency  percentage
0          1.0       2633       80.62
1          2.0        412       12.61
2          3.0         44        1.35
3          4.0         76        2.33
4          5.0         29        0.89
5          6.0         27        0.83
6          7.0         45        1.38

   computer_internet  frequency  percentage
0                1.0       1975       60.20
1                2.0        351       10.70
2                3.0         58        1.77
3                4.0         92        2.80
4                5.0         88        2.68
5                6.0        120        3.66
6                7.0        597       18.20

   exercising  frequency  percentage
0         1.0        402       12.44
1         2.0        721       22.31
2         3.0        251        7.77
3         4.0        309        9.56
4         5.0        224        6.93
5         6.0        502       15.53
6         7.0        823       25.46

   walking  frequency  percentage
0      1.0        755       23.04
1      2.0        828       25.27
2      3.0        270        8.24
3      4.0        342       10.44
4      5.0        235        7.17
5      6.0        435       13.27
6      7.0        412       12.57

   education_training  frequency  percentage
0                 1.0         12        0.37
1                 2.0         39        1.20
2                 3.0         70        2.15
3                 4.0         70        2.15
4                 5.0        250        7.67
5                 6.0        737       22.60
6                 7.0       2083       63.88

   trouble_falling_asleep  frequency  percentage
0                    -8.0          3        0.02
1                     1.0       2409       16.74
2                     2.0       5286       36.73
3                     3.0       6635       46.10
4                     8.0         59        0.41
5                     9.0          1        0.01

   waking_at_night  frequency  percentage
0             -8.0          5        0.03
1              1.0       3353       23.30
2              2.0       5928       41.19
3              3.0       5043       35.04
4              8.0         61        0.42
5              9.0          3        0.02

   waking_too_early  frequency  percentage
0              -8.0          5        0.03
1               1.0       2034       14.13
2               2.0       5299       36.82
3               3.0       7010       48.70
4               8.0         43        0.30
5               9.0          2        0.01

   feeling_rested  frequency  percentage
0            -8.0          3        0.02
1             1.0       7182       49.90
2             2.0       4660       32.38
3             3.0       2507       17.42
4             8.0         39        0.27
5             9.0          2        0.01

Also made a table which shows the min, max, mean age, mean of sitting hours, minutes and mean of delayed and imidiate recall. This is to further understand the overall population.

In [ ]:
numeric_summary = duckdb.sql("SELECT ROUND(AVG(age), 2) AS mean_age, MIN(age) " \
"AS min_age, MAX(age) AS max_age, ROUND(AVG(immediate_recall), 2) " \
"AS mean_immediate_recall, ROUND(AVG(delayed_recall), 2) " \
"AS mean_delayed_recall, ROUND(AVG(sitting_hours), 2) " \
"AS mean_sitting_hours, ROUND(AVG(sitting_minutes), 2) " \
"AS mean_sitting_minutes FROM hrs").df()
display(numeric_summary)

,mean_age,min_age,max_age,mean_immediate_recall,mean_delayed_recall,mean_sitting_hours,mean_sitting_minutes
0,69.11,29.0,108.0,5.3,4.27,8.4,3.14

### HRS Summary by Age Group

Next, we will create `grouped_hrs`, which summarizes the HRS data by age group. This is not the same as ATUS which means when we compare data we will have to divide even furthur, however HRS focuses on older population which means we dont have data for less than 25yr old.

For each age group, we calculate the number of participants and summarize the main leisure, sleep, memory, and sedentary-behavior variables. This allows us to identify general differences in leisure activities and health outcomes across age groups. It is important to highlight averages of HRS response codes, not average minutes or percentages.

- 25 - 44
- 45 - 64
- 65+

In [ ]:
grouped_hrs = duckdb.sql("SELECT age_group, COUNT(*) " \
"AS num_participants, ROUND(AVG(reading), 2) " \
"AS avg_reading, ROUND(AVG(watching_tv), 2) " \
"AS avg_tv, ROUND(AVG(computer_internet), 2) " \
"AS avg_computer, ROUND(AVG(exercising), 2) " \
"AS avg_exercising, ROUND(AVG(walking), 2) " \
"AS avg_walking, ROUND(AVG(trouble_falling_asleep), 2) " \
"AS avg_trouble_falling_asleep, ROUND(AVG(feeling_rested), 2) " \
"AS avg_feeling_rested, ROUND(AVG(immediate_recall), 2) " \
"AS avg_immediate_recall, ROUND(AVG(delayed_recall), 2) " \
"AS avg_delayed_recall, ROUND(AVG(sitting_hours), 2) " \
"AS avg_sitting_hours FROM (SELECT *, CASE WHEN age BETWEEN 15 AND 24 THEN '15-24' WHEN age BETWEEN 25 AND 44 THEN '25-44' " \
"WHEN age BETWEEN 45 AND 64 THEN '45-64' ELSE '65+' END " \
"AS age_group FROM hrs WHERE age IS NOT NULL) " \
"GROUP BY age_group ORDER BY CASE age_group WHEN '15-24' THEN 1 WHEN '25-44' THEN 2 WHEN '45-64' THEN 3 ELSE 4 END").df()

display(grouped_hrs)

,age_group,num_participants,avg_reading,avg_tv,avg_computer,avg_exercising,avg_walking,avg_trouble_falling_asleep,avg_feeling_rested,avg_immediate_recall,avg_delayed_recall,avg_sitting_hours
0,25-44,81,3.29,2.43,2.00,3.00,2.57,2.28,1.86,5.75,4.62,6.51
1,45-64,5156,3.29,1.48,2.20,4.23,3.22,2.28,1.79,5.71,4.67,7.63
2,65+,9156,2.68,1.33,2.79,4.26,3.53,2.34,1.63,5.04,4.02,8.86

### Checking Variables for missing values

Before using the cognition variables in our analysis, we will inspect the distribution of the immediate and delayed word-recall scores. These variables are already numeric measures of memory performance. Additionally, HRS leisure variables represent frequency categories rather than minutes spent on each activity. However, checking their values helps us identify missing values or unexpected codes before using them in later analysis.

In [ ]:
missing_summary = pd.DataFrame({"missing_values": hrs.isna().sum(), "missing_percent": (hrs.isna().mean() * 100).round(2)})
display(missing_summary)

                        missing_values  missing_percent
hhid                                 0             0.00
pn                                   0             0.00
education_training               11137            77.35
reading                          11131            77.31
watching_tv                      11132            77.32
computer_internet                11117            77.21
exercising                       11166            77.55
walking                          11121            77.24
immediate_recall                  2727            18.94
delayed_recall                    2787            19.36
trouble_falling_asleep               5             0.03
waking_at_night                      5             0.03
waking_too_early                     5             0.03
feeling_rested                       5             0.03
sitting_minutes                      6             0.04
sitting_hours                        5             0.03
age                                  5             0.03

% has_lb_data by age group; age distribution of full HRS vs LB subset

### Creating Total Sitting Time

The HRS records daily sitting time using separate variables for hours and minutes. These variables represent two components of the same reported sitting time. We keep
the original variables in our dataset, but remove special survey response codes (negative time) before using them in calculations.

After cleaning, we combine the hour and minute components into a single variable representing total daily sitting time in minutes. This provides a more interpretable measure of sedentary behavior for our later analysis.

In [ ]:
hrs["sitting_hours"] = hrs["sitting_hours"].replace(-8, np.nan)
hrs["sitting_minutes"] = hrs["sitting_minutes"].replace(-8, np.nan)
hrs["sitting_total_minutes"] = hrs["sitting_hours"] * 60 + hrs["sitting_minutes"]

display(duckdb.sql("SELECT ROUND(AVG(sitting_total_minutes), 2) " \
"AS avg_sitting_minutes, MIN(sitting_total_minutes) " \
"AS min_sitting_minutes, MAX(sitting_total_minutes) " \
"AS max_sitting_minutes FROM hrs").df())

display(duckdb.sql("SELECT hhid, pn, sitting_hours, sitting_minutes, sitting_total_minutes FROM hrs WHERE sitting_total_minutes > 1440 ORDER BY sitting_total_minutes DESC").df())

   avg_sitting_minutes  min_sitting_minutes  max_sitting_minutes
0               524.37                  0.0               6039.0

       hhid   pn  sitting_hours  sitting_minutes  sitting_total_minutes
0    038761  040           99.0             99.0                 6039.0
1    050766  040           99.0             99.0                 6039.0
2    059897  010           99.0             99.0                 6039.0
3    544871  020           99.0             99.0                 6039.0
4    077714  010           99.0             99.0                 6039.0
..      ...  ...            ...              ...                    ...
434  542510  010           98.0              0.0                 5880.0
435  543075  010           98.0              0.0                 5880.0
436  556943  020           98.0              0.0                 5880.0
437  075988  020           98.0              0.0                 5880.0
438  915013  020           24.0             60.0                 1500.0

[439 rows x 5 columns]

After combining the sitting-hours and sitting-minutes variables, we found several values that cannot represent actual daily sitting time. For example, some respondents have values of 98 or 99 hours, and one observation produces more than 24 hours of sitting in a single day.

To prevent these special or invalid values from affecting our summary statistics, we create cleaned versions of the sitting-time variables. Valid sitting hours must fall between 0 and 24, while the minutes component must fall between 0 and 59. We then calculate total sitting time and treat totals greater than 1,440 minutes (24 hours) as missing.

In [ ]:
hrs["sitting_hours_clean"] = hrs["sitting_hours"].where(hrs["sitting_hours"].between(0, 24), np.nan)
hrs["sitting_minutes_clean"] = hrs["sitting_minutes"].where(hrs["sitting_minutes"].between(0, 59), np.nan)
hrs["sitting_total_minutes"] = hrs["sitting_hours_clean"] * 60 + hrs["sitting_minutes_clean"]
hrs.loc[hrs["sitting_total_minutes"] > 1440, "sitting_total_minutes"] = np.nan

display(duckdb.sql("SELECT ROUND(AVG(sitting_total_minutes), 2) " \
"AS avg_sitting_minutes, MIN(sitting_total_minutes) " \
"AS min_sitting_minutes, MAX(sitting_total_minutes) " \
"AS max_sitting_minutes FROM hrs").df())

display(duckdb.sql("SELECT COUNT(*) AS invalid_sitting_values FROM hrs WHERE sitting_total_minutes > 1440").df())

   avg_sitting_minutes  min_sitting_minutes  max_sitting_minutes
0               333.11                  0.0               1440.0

   invalid_sitting_values
0                       0

### Cleaning Sleep Variables

The HRS sleep variables contain three substantive response categories, coded as `1`, `2`, and `3`, as well as additional special response codes such as `-8`, `8`, and `9`. Because these special codes do not represent actual levels of sleep difficulty or restfulness, we convert them to missing values before calculating averages or using the variables in exploratory analysis. We keep the original variables and create cleaned versions for analysis.

In [ ]:
hrs["trouble_falling_asleep_clean"] = hrs["trouble_falling_asleep"].where(hrs["trouble_falling_asleep"].isin([1, 2, 3]), np.nan)
hrs["waking_at_night_clean"] = hrs["waking_at_night"].where(hrs["waking_at_night"].isin([1, 2, 3]), np.nan)
hrs["waking_too_early_clean"] = hrs["waking_too_early"].where(hrs["waking_too_early"].isin([1, 2, 3]), np.nan)
hrs["feeling_rested_clean"] = hrs["feeling_rested"].where(hrs["feeling_rested"].isin([1, 2, 3]), np.nan)

display(duckdb.sql("SELECT trouble_falling_asleep_clean, COUNT(*) AS frequency FROM hrs GROUP BY trouble_falling_asleep_clean ORDER BY trouble_falling_asleep_clean").df())
display(duckdb.sql("SELECT waking_at_night_clean, COUNT(*) AS frequency FROM hrs GROUP BY waking_at_night_clean ORDER BY waking_at_night_clean").df())
display(duckdb.sql("SELECT waking_too_early_clean, COUNT(*) AS frequency FROM hrs GROUP BY waking_too_early_clean ORDER BY waking_too_early_clean").df())
display(duckdb.sql("SELECT feeling_rested_clean, COUNT(*) AS frequency FROM hrs GROUP BY feeling_rested_clean ORDER BY feeling_rested_clean").df())

   trouble_falling_asleep_clean  frequency
0                           1.0       2409
1                           2.0       5286
2                           3.0       6635
3                           NaN         68

   waking_at_night_clean  frequency
0                    1.0       3353
1                    2.0       5928
2                    3.0       5043
3                    NaN         74

   waking_too_early_clean  frequency
0                     1.0       2034
1                     2.0       5299
2                     3.0       7010
3                     NaN         55

   feeling_rested_clean  frequency
0                   1.0       7182
1                   2.0       4660
2                   3.0       2507
3                   NaN         49

### Cleaning Leisure Activity Variables

The HRS leisure variables measure how frequently respondents participate in activities such as reading, television viewing, computer use, exercise, walking, and educational
activities. These variables use response codes from 1 through 7. We inspect and clean these variables so that only valid response codes from 1 through 7 are retained. Any other numeric values would be treated as missing.

In [ ]:
hrs["reading_clean"] = hrs["reading"].where(hrs["reading"].between(1, 7), np.nan)
hrs["watching_tv_clean"] = hrs["watching_tv"].where(hrs["watching_tv"].between(1, 7), np.nan)
hrs["computer_internet_clean"] = hrs["computer_internet"].where(hrs["computer_internet"].between(1, 7), np.nan)
hrs["exercising_clean"] = hrs["exercising"].where(hrs["exercising"].between(1, 7), np.nan)
hrs["walking_clean"] = hrs["walking"].where(hrs["walking"].between(1, 7), np.nan)
hrs["education_training_clean"] = hrs["education_training"].where(hrs["education_training"].between(1, 7), np.nan)

display(duckdb.sql("SELECT reading_clean, COUNT(*) AS frequency FROM hrs GROUP BY reading_clean ORDER BY reading_clean").df())
display(duckdb.sql("SELECT watching_tv_clean, COUNT(*) AS frequency FROM hrs GROUP BY watching_tv_clean ORDER BY watching_tv_clean").df())
display(duckdb.sql("SELECT exercising_clean, COUNT(*) AS frequency FROM hrs GROUP BY exercising_clean ORDER BY exercising_clean").df())

   reading_clean  frequency
0            1.0       1253
1            2.0        644
2            3.0        224
3            4.0        349
4            5.0        309
5            6.0        221
6            7.0        267
7            NaN      11131

   watching_tv_clean  frequency
0                1.0       2633
1                2.0        412
2                3.0         44
3                4.0         76
4                5.0         29
5                6.0         27
6                7.0         45
7                NaN      11132

   exercising_clean  frequency
0               1.0        402
1               2.0        721
2               3.0        251
3               4.0        309
4               5.0        224
5               6.0        502
6               7.0        823
7               NaN      11166

### Cleaning Cognition Variables

The HRS cognition variables measure the number of words correctly recalled during the immediate and delayed word-recall tasks. Valid scores range from 0 to 10 words. To ensure that unexpected values do not affect our analysis, we create cleaned versions that retain only scores between 0 and 10. Missing responses remain recorded as `NaN`.

In [ ]:
hrs["immediate_recall_clean"] = hrs["immediate_recall"].where(hrs["immediate_recall"].between(0, 10), np.nan)
hrs["delayed_recall_clean"] = hrs["delayed_recall"].where(hrs["delayed_recall"].between(0, 10), np.nan)
display(duckdb.sql("SELECT immediate_recall_clean, COUNT(*) AS frequency FROM hrs GROUP BY immediate_recall_clean ORDER BY immediate_recall_clean").df())
display(duckdb.sql("SELECT delayed_recall_clean, COUNT(*) AS frequency FROM hrs GROUP BY delayed_recall_clean ORDER BY delayed_recall_clean").df())

    immediate_recall_clean  frequency
0                      0.0         75
1                      1.0        126
2                      2.0        426
3                      3.0       1072
4                      4.0       1989
5                      5.0       2672
6                      6.0       2499
7                      7.0       1678
8                      8.0        743
9                      9.0        301
10                    10.0         90
11                     NaN       2727

    delayed_recall_clean  frequency
0                    0.0        698
1                    1.0        507
2                    2.0        976
3                    3.0       1712
4                    4.0       2260
5                    5.0       2317
6                    6.0       1581
7                    7.0        905
8                    8.0        424
9                    9.0        179
10                  10.0         52
11                   NaN       2787